#PBS -j oe
#PBS -N RigidBodies
#PBS -m a
#PBS -m b
#PBS -o $HOME/scratch/rigid_bodies/data/pbs_$ARG_SEED.log
#PBS -M skriegma@uvm.edu
#PBS -l nodes=1:ppn=12,pmem=2gb,pvmem=2gb
#PBS -l walltime=3:00:00
#PBS -q shortq

PATH=$HOME/anaconda/bin:$PATH
cd $HOME/scratch/rigid_bodies/pyrosim/evodevo/
PYTHONPATH=$HOME/scratch/rigid_bodies/pyrosim/ $HOME/anaconda/bin/python ./pbs_rigid_evo_test.py $ARG_SEED
